version: '2'


services:

    # MySQL database shared with tomcat containers.
    db:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: ATHENEA
        MYSQL_USER: athenea
        MYSQL_PASSWORD: athenea
      volumes:
        - "./sql:/docker-entrypoint-initdb.d"

    # First node of the first Tomcat virtual host.
    tomcat:
      restart: always
      image: tomcat
      ports:
        - "8081:8080"
      volumes:
        - ./target/users_organizations-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/users_organizations-microservice.war
      links:
        - db:db_org
      depends_on:
        - "db"